### ISSUE TITLE
My Schedule -Time Remaining

### ISSUE THREAD

**Issue by HaoZiOwO** [cse442-at-ub/cse442-semester-project-368#25]
The user wants to see the time remaining until the next schedule, so we need to display the remaining time under "My Schedule" page.

**Comment by cjw531** [comment]
### Task Test

- [x] Based on the current time showing on top, calculate the remaining time for each schedule.
- [x] Make a slot for showing a remaining time on the right side of the each of the schedule.
- [x] Put the calculated remaining time on the right side of each schedule.
- [x] Check at first (whether the remaining time is calculated correctly or not; then leave it for some time then re-check it whether it calculates the remaining time based on the current time.
