### ISSUE TITLE
My Schedule -Add

### ISSUE THREAD

**Issue by mzhang54** [cse442-at-ub/cse442-semester-project-368#39]
We need to build "add" today's schedule feature. It should give a pop-up window with input slots, when the user clicks the "Add Daily Schedule" floating button (#45).

**Comment by dr72** [comment]
### Task Test

- [x] Prompt the user to fill out the following information when the user press the "Add Schedule" floating button: title, start time, end time, end date, details. *Note that "My Schedule" page only supports the schedule starting from today.
- [x] If the user did not fill out the information, prompt them to fill it up, except for the "details" section.
- [x] Update the database once the user press the save button, based on the designed database in #50
- [x] Add some mock schedule via Android application and compare whether it gets added properly or not on myphpadmin or thru cheshire server on terminal.
