### ISSUE TITLE
CompactCalendarView API -View Schedule on Calendar

### ISSUE THREAD

**Issue by cjw531** [cse442-at-ub/cse442-semester-project-368#52]
Implement this API so that a user can intuitively interact with the calendar to add/edit/view/delete their schedule. The API needs to mark the schedule over the calendar itself.

**Comment by cjw531** [comment]
### Task Test

- [ ] Mark the schedule on the calendar API.
- [ ] Color-code today.
- [ ] The user should be able to swipe left (previous month) and right (future month).
- [ ] Fix the current bug which does not update the month after the swiping gesture.
- [ ] When the user navigates to the "Calendar" page, the user should be able to see the current day is marked (color-coded, encircled), and should be able to see the today's schedule unless the user clicks other day.

**Comment by cjw531** [comment]
### Task Test

- Import CompactCalendar API
- Mark the schedule on the calendar API.
- Color-code today: color should be consistent with the current application theme.
- The user should be able to swipe left (previous month) and right (future month).
- Once the user swipe, it sets into the first day of the month as clicked date, and showing the first day of month's schedule list below.
- Fix the current bug which does not update the month after the swiping gesture.
- When the user navigates to the "Calendar" page, the user should be able to see the current day is marked (color-coded, encircled), and should be able to see the today's schedule unless the user clicks other day.
- When the user clicks the date, that clicked date should be colored with a different color than the today's color. It should be distinctive so that the user could notice.
- When the user clicks the date, the schedule list below the calendar should be showing the schedule for that selected day. (connect its onclick date with the database fetching)
- The calendar API should be able to show the schedule in dots over the calendar, based on the user's schedule database.
- The calendar API should be able to color-code the date if a user selected some other day other than today.
- Whenever the user clicks the different date, the schedule list below the calendar API should be modified to that clicked date's schedule.
