### ISSUE TITLE
My Schedule - Get Schedule from database

### ISSUE THREAD

**Issue by cjw531** [cse442-at-ub/cse442-semester-project-368#54]
Based on the designed database, we need to print out the list of the user's daily schedule, under the remaining time widget (#25).

**Comment by cjw531** [comment]
### Task Test

- [x] Display the current time on top.
- [x] Below the current time, it has a horizontal line to divide up the current time and the user's daily schedule list.
- [x] The schedule list should be displaying the daily schedules only, based on the current date.
- [x] The daily schedule should be displaying the schedule based on the designed database.
- [x] The schedule list should be up-to-dated based on the user's add/edit/delete action. (#39, #55, #56)
- [x] Daily schedule is sorted based on its starting time.
- [x] Next to the schedule, on the right side, it displays a remaining time until the schedule begins. (#52)
- [x] Once the schedule started, it is not displayed in the list anymore.
- [x] Do some action (add/edit/delete) on Android application then compare whether it gets updated properly or not on myphpadmin or thru cheshire server on terminal.
