### ISSUE TITLE
View Monthly Schedule on Calendar

### ISSUE THREAD

**Issue by cjw531** [cse442-at-ub/cse442-semester-project-368#58]
As a user, I want to view my schedule in calendar, so I can intuitively view what I have to do for month.

**Comment by cjw531** [comment]
### Task Test

- [ ] When the user clicks the date, the schedule list below the calendar should be showing the schedule for that selected day.
- [ ] The calendar API should be able to show the schedule in dots over the calendar, based on the user's schedule database.
- [ ] The calendar API should be able to color-code the date if a user selected some other day other than today.

**Comment by cjw531** [comment]
### Acceptance Test

1. Navigate to the "Calendar" page.
2. It should show the current monthly calendar on the upper page; and shows today's schedule below (today is initially marked on the calendar with green color)
3. Once you click other date, it will marked into red/pink color and shows that **marked day's schedule**. *Note that today is still marked with green color to indicate that marked day is today.
*Note that the schedule listed below is NOT sorted, based on its start time, yet.
4. Similar to "My Schedule" (#2), you can add schedule with floating button in right-bottom of the screen, edit and delete your schedule by clicking a certain schedule from the list.
